# gradle
java_version=17
use_mixin=true
upload_debug=true

# minecraft
minecraft_version=1.16.5
parchmentmc_version=1.16.5:2022.03.06

# mod
display_name=SquidNoGlitch
archives_base_name=squidnoglitch
mod_id=squidnoglitch
mod_description=A tiny mod that fixes various vanilla bugs with the squid
maven_group=com.stevekung.squidnoglitch
mod_version=1.0.4
release_type=release
enabled_platforms=fabric,forge

# curseforge
curseforge_project_id=923510

# modrinth
modrinth_project_id=squid-no-glitch

# fabric
fabric_loader_version=0.17.3

# forge
forge_version=36.2.34