# gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
java_version=21
use_mixin=true
upload_debug=true

# minecraft
minecraft_version=1.21.10
parchmentmc_version=1.21.10:2025.10.12

# mod
display_name=SquidNoGlitch
archives_base_name=squidnoglitch
mod_id=squidnoglitch
mod_description=A tiny mod that fixes various vanilla bugs with the squid
maven_group=com.stevekung.squidnoglitch
mod_version=1.0.4
release_type=release
enabled_platforms=fabric,neoforge
quilt_compatible=true

# curseforge
curseforge_project_id=923510

# modrinth
modrinth_project_id=squid-no-glitch

# fabric
fabric_loader_version=0.17.3

# neoforge
neoforge_version=21.10.28-beta