# gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
use_mixin=true
upload_debug=true

# minecraft
minecraft_version=1.12.2
mapping_channel=stable
mapping_version=39

# mod
display_name=SquidNoGlitch
archives_base_name=squidnoglitch
mod_id=squidnoglitch
mod_description=A tiny mod that fixes various vanilla bugs with the squid
maven_group=com.stevekung.squidnoglitch
mod_version=1.0.0
release_type=release
mixin_booter_version=10.7

# curseforge
curseforge_project_id=923510

# modrinth
modrinth_project_id=squid-no-glitch