package com.stevekung.squidnoglitch;

import java.util.Collections;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = "squidnoglitch", name = "SquidNoGlitch", version = Tags.VERSION, dependencies = SquidNoGlitch.MAIN_DEPENDENCIES)
public class SquidNoGlitch
{
    public static final Logger LOGGER = LogManager.getLogger("SquidNoGlitch");
    public static final String URL = "https://www.curseforge.com/minecraft/mc-mods/squid-no-glitch";
    protected static final String MAIN_DEPENDENCIES = "required-after:unimixins@[0.1.22,); ";

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        LOGGER.info("SquidNoGlitch loaded, No more squids glitch through the block!");
        initModInfo(event.getModMetadata());
    }

    private static void initModInfo(ModMetadata info)
    {
        info.autogenerated = false;
        info.modId = "squidnoglitch";
        info.name = "SquidNoGlitch";
        info.version = Tags.VERSION;
        info.description = "A tiny mod that fixes various vanilla bugs with the squid";
        info.url = URL;
        info.logoFile = "/logo.png";
        info.authorList = Collections.singletonList("SteveKunG");
    }
}