name: publish
on:
  push:
    tags: [ '*' ]

permissions:
  contents: write

jobs:
  release-tags:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/release-tags.yml@master
    secrets:
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_API_TOKEN }}